# Generated by Django 5.1.4 on 2024-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imag_url',
        ),
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
